### ISSUE TITLE
vague phrasing

### ISSUE THREAD

**Issue by mantelt** [turcantuna/SMB_Assembly-Manual#5]
https://github.com/turcantuna/SMB_Assembly-Manual/wiki/Aluminium-Profiles

> The end threads have to be processed either with a hand drill or in the workshop. The workshop will require the drawings as well as the .STEP files located here.

Above sentence somehow confuses me. The technical drawings contain all necessary information, correct?
Maybe you could change it to:
```
Some of the aluminium profiles have end threads as shown in the technical drawings. The profiles can be ordered directly from ITEM with end threads. Alternatively, the end threads can be processed either with a hand drill or in the workshop. (The ETH workshop in LEO will require the drawings as well as the .STEP files located here.)
```

**Comment by turcantuna** [comment]
Updated
